spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

jwt.validity=3600000

jwt.secret=${JWT_SECRET}
jwt.cookie.name=token
jwt.cookie.max-age=86400
jwt.cookie.secure=false
jwt.cookie.http-only=true
jwt.cookie.same-site=Strict

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}

spring.rabbitmq.dynamic=true
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.initial-interval=3000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

SYSADMIN_USER=${SYSADMIN_USER:admin}
SYSADMIN_EMAIL=${SYSADMIN_EMAIL:admin@admin.com}
SYSADMIN_PASSWORD=${SYSADMIN_PASSWORD:admin123}

# Script de inicialização de dados (pode ser sobrescrito por variável de ambiente)
app.initialize-data=${INITIALIZE_DATA:false}