spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

jwt.validity=3600000

jwt.secret=RpYSBhbGd16W0gZGVzY29icmlyRX9yaWEgcXVlIGRpeitYSB0ZWdWUsIHNlIHVtIG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.dynamic=true
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.initial-interval=3000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=simlady-storage-container

SYSADMIN_USER=admin
SYSADMIN_EMAIL=admin@admin.com
SYSADMIN_PASSWORD=admin123