spring.datasource.url=jdbc:postgresql://localhost:5432/simlady
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

jwt.validity=3600000

jwt.secret=RpYSBhbGd16W0gZGVzY29icmlyRX9yaWEgcXVlIGRpeitYSB0ZWdWUsIHNlIHVtIG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=123456
spring.rabbitmq.dynamic=true
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.initial-interval=3000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

azure.storage.connection-string=UseDevelopmentStorage=true
azure.storage.container-name=imagens